#.......................................
#ARITHEMATIC OPERATORS
#............................................
print(2+3)#addition
#.................................
print(3-2)#Subtraction
#.................................
print(2*3)#multiplication
#.................................
print(10/5)#division
#.................................
print(10//5)#if our  result is in decimal so only before decimal interger is accepted
#for example 2/3=0.6666 so here the answer will be 0 because this method had only accepted 0 as answer
#.................................
print(10%5)#modulus#remainder is printed
#.................................
print(2**3)#exponential form of the number are printed for.example . 2 raise to 3 is 8 so the answer printed in thi
#in this case is 8
#.................................